/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BoostIcon: typeof import('./src/components/boost-icon.vue')['default']
    CreateTeams: typeof import('./src/components/createTeams.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElCountdown: typeof import('element-plus/es')['ElCountdown']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDivier: typeof import('element-plus/es')['ElDivier']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FocusIcon: typeof import('./src/components/focusIcon.vue')['default']
    FocusIcons: typeof import('./src/components/focusIcons.vue')['default']
    InProgress: typeof import('./src/components/inProgress.vue')['default']
    Moonlight: typeof import('./src/components/mini/moonlight.vue')['default']
    PreviewItem: typeof import('./src/components/previewItem.vue')['default']
    RefreshData: typeof import('./src/components/refreshData.vue')['default']
    RelicIcon: typeof import('./src/components/relic-icon.vue')['default']
    RotateCard: typeof import('./src/components/rotate-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RyuAdd: typeof import('./src/components/ryu-add.vue')['default']
    RyuCopy: typeof import('./src/components/ryuCopy.vue')['default']
    RyuEmpty: typeof import('./src/components/ryuEmpty.vue')['default']
    RyuFooter: typeof import('./src/components/ryu-footer.vue')['default']
    RyuHeader: typeof import('./src/components/ryu-header.vue')['default']
    RyuIcon: typeof import('./src/components/ryu-icon.vue')['default']
    RyuSkeleton: typeof import('./src/components/ryuSkeleton.vue')['default']
    RyuState: typeof import('./src/components/ryuState.vue')['default']
    RyuStatistic: typeof import('./src/components/ryu-statistic.vue')['default']
    Sunrise: typeof import('./src/components/mini/sunrise.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    WarframeIcon: typeof import('./src/components/warframeIcon.vue')['default']
    XkywTeam: typeof import('./src/components/xkywTeam.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
